package rx

import (
	"time"
)

// Interval creates a channel that emits an integer at a fixed interval
func Interval(d time.Duration, options ...Option) <-chan int {
	out := observableCh[int](options...)

	go func() {
		defer close(out)

		ticker := time.NewTicker(d)
		defer ticker.Stop()

		for i := 0; ; i++ {
			<-ticker.C
			out <- i
		}
	}()

	return out
}

// From creates a channel that emits the values from the provided slice
func From[T any](vv []T, options ...Option) <-chan T {
	out := observableCh[T](options...)

	go func() {
		defer close(out)

		for _, v := range vv {
			out <- v
		}
	}()

	return out
}

// Of creates a channel that emits the provided values.
// Please note that this function is not receive Option, so the channel is always no buffer.
// If you want to set buffer size, please use From function instead
func Of[T any](vv ...T) <-chan T {
	return From(vv)
}

// Range creates a channel that emits a range of integers
func Range(start int, count int, options ...Option) <-chan int {
	out := observableCh[int](options...)

	go func() {
		defer close(out)

		for i := start; i < start+count; i++ {
			out <- i
		}
	}()

	return out
}

// Generate creates a channel that emits values generated by the provided seed, condition, iterate, and resultSelector functions
func Generate[T any, R any](seed T, condition func(v T) bool, iterate func(v T) T, resultSelector func(v T) R, options ...Option) <-chan R {
	out := observableCh[R](options...)

	go func() {
		defer close(out)

		for v := seed; condition(v); v = iterate(v) {
			out <- resultSelector(v)
		}
	}()

	return out
}
